export const ACTIONS = {
    FWD: 1,
    BWD: 2,
    LEFT: 3,
    RIGHT: 4,
    JUMP: 5,
    DASH: 6,
    ATTACK_LEFT: 7,
    ATTACK_RIGHT: 8,
    SPELL_1: 9,
    SPELL_2: 10,
    SPELL_3: 11,
    SPELL_4: 12,
    INVENTORY: 13,
    HOME: 14,
    WORLD1: 15,
    DEVFLY: 16,
}

export const defaultBinds = {
    '0': ACTIONS.ATTACK_LEFT,
    '2': ACTIONS.ATTACK_RIGHT,
    'KeyW': ACTIONS.FWD,
    'KeyS': ACTIONS.BWD,
    'KeyA': ACTIONS.LEFT,
    'KeyD': ACTIONS.RIGHT,
    'Space': ACTIONS.JUMP,
    'ShiftLeft': ACTIONS.DASH,
    'KeyC': ACTIONS.INVENTORY,
    'KeyT': ACTIONS.HOME,
    'Digit1': ACTIONS.SPELL_1,
    'Digit2': ACTIONS.SPELL_2,
    'Digit3': ACTIONS.SPELL_3,
    'Digit4': ACTIONS.SPELL_4,
    'KeyF': ACTIONS.DEVFLY,
}