export const ACTIONS = {
    FWD: 1 << 0,
    BWD: 1 << 1,
    LEFT: 1 << 2,
    RIGHT: 1 << 3,
    JUMP: 1 << 4,
    DASH: 1 << 5,
    ATTACK_LEFT: 1 << 6,
    ATTACK_RIGHT: 1 << 7,
    SPELL_1: 1 << 8,
    SPELL_2: 1 << 9,
    SPELL_3: 1 << 10,
    SPELL_4: 1 << 11,
    INVENTORY: 1 << 12,
    HOME: 1 << 13,
    WORLD1: 1 << 14,
    DEVFLY: 1 << 15,
}

export const defaultBinds = {
    '0': ACTIONS.ATTACK_LEFT,
    '2': ACTIONS.ATTACK_RIGHT,
    'KeyW': ACTIONS.FWD,
    'KeyS': ACTIONS.BWD,
    'KeyA': ACTIONS.LEFT,
    'KeyD': ACTIONS.RIGHT,
    'Space': ACTIONS.JUMP,
    'ShiftLeft': ACTIONS.DASH,
    'KeyC': ACTIONS.INVENTORY,
    'KeyT': ACTIONS.HOME,
    'Digit1': ACTIONS.SPELL_1,
    'Digit2': ACTIONS.SPELL_2,
    'Digit3': ACTIONS.SPELL_3,
    'Digit4': ACTIONS.SPELL_4,
    'KeyF': ACTIONS.DEVFLY,
}