export const Actions = {
    FWD: 1,
    BWD: 2,
    LEFT: 3,
    RIGHT: 4,
    JUMP: 5,
    DASH: 6,
    ATTACK_LEFT: 7,
    ATTACK_RIGHT: 8,
    SPELL_1: 9,
    SPELL_2: 10,
    SPELL_3: 11,
    SPELL_4: 12,
    INVENTORY: 13,
    HOME: 14,
    WORLD1: 15,
}